name: Standard Notes ARM Builder

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  release-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get latest Standard Notes release
        id: release
        run: |
          RELEASE=$(curl -s https://api.github.com/repos/standardnotes/app/releases/latest | jq -r .tag_name)

          VERSION=$(echo "$RELEASE" | sed 's/^@standardnotes\/desktop@//')

          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          echo "Latest release:"
          echo "$RELEASE"

          echo ""
          echo "Detected version:"
          echo "$VERSION"

      - name: Verify variables
        run: |
          echo "Release: $RELEASE"
          echo "Version: $VERSION"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check existing image
        run: |
          docker manifest inspect ghcr.io/fred-head/standardnotes-arm-web:latest
