name: Standard Notes ARM Builder

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get latest Standard Notes release
        run: |
          RELEASE=$(curl -s https://api.github.com/repos/standardnotes/app/releases/latest | jq -r .tag_name)

          echo "Latest Standard Notes Release:"
          echo "$RELEASE"
